In [2]:
from src.imnfs.model import RNF,NFSet
import numpy as np
import random

# data test

In [3]:
def nf(o,c):
#    o = int(input("Number of objects: "))
#    c = int(input("Number of criteria: "))
#    s = int(input("Seed: "))
    random.seed(7)
    out = []
    for i in range(c):
        out_c = []
        for j in range(o):
            out_o = []
            for k in range(4):
                if k == 0:
                    out_o.append(random.randint(1,9)/10)
                else:
                    out_o.append(random.randint(1,9)/10)
            out_c.append(out_o)
        out.append(out_c)
    return out

In [4]:
ip = nf(4,5) 
print(np.array(ip))

[[[0.6 0.3 0.7 0.1]
  [0.2 0.9 0.2 0.6]
  [0.1 0.9 0.4 0.1]
  [0.2 0.7 0.7 0.2]]

 [[0.4 0.2 0.9 0.7]
  [0.1 0.2 0.4 0.1]
  [0.7 0.1 0.4 0.1]
  [0.9 0.3 0.5 0.7]]

 [[0.3 0.9 0.2 0.5]
  [0.9 0.3 0.2 0.4]
  [0.6 0.2 0.9 0.2]
  [0.1 0.4 0.8 0.9]]

 [[0.7 0.6 0.8 0.8]
  [0.6 0.5 0.4 0.3]
  [0.4 0.2 0.5 0.9]
  [0.8 0.6 0.8 0.5]]

 [[0.2 0.2 0.9 0.7]
  [0.3 0.6 0.3 0.8]
  [0.7 0.1 0.2 0.9]
  [0.6 0.6 0.6 0.8]]]


In [5]:
def neg(a):
    out = []
    for i in range(len(a)):
        out.append([1-j for j in a[i]])
    return out
#########
def rnf(a,m):
    out = []
    for i in range(len(a)):
        if i in m:
            out.append(neg(a[i]))
        else:
            out.append(a[i])
    return out

In [6]:
cost = [3]  # Complement first and third matrices
mat = rnf(ip, cost)
mat

[[[0.6, 0.3, 0.7, 0.1],
  [0.2, 0.9, 0.2, 0.6],
  [0.1, 0.9, 0.4, 0.1],
  [0.2, 0.7, 0.7, 0.2]],
 [[0.4, 0.2, 0.9, 0.7],
  [0.1, 0.2, 0.4, 0.1],
  [0.7, 0.1, 0.4, 0.1],
  [0.9, 0.3, 0.5, 0.7]],
 [[0.3, 0.9, 0.2, 0.5],
  [0.9, 0.3, 0.2, 0.4],
  [0.6, 0.2, 0.9, 0.2],
  [0.1, 0.4, 0.8, 0.9]],
 [[0.30000000000000004, 0.4, 0.19999999999999996, 0.19999999999999996],
  [0.4, 0.5, 0.6, 0.7],
  [0.6, 0.8, 0.5, 0.09999999999999998],
  [0.19999999999999996, 0.4, 0.19999999999999996, 0.5]],
 [[0.2, 0.2, 0.9, 0.7],
  [0.3, 0.6, 0.3, 0.8],
  [0.7, 0.1, 0.2, 0.9],
  [0.6, 0.6, 0.6, 0.8]]]

In [7]:
temp =  NFSet(data= ip)

In [8]:
rnf = RNF(temp, cost= cost)

In [9]:
rnf.data

array([[[0.6, 0.3, 0.7, 0.1],
        [0.2, 0.9, 0.2, 0.6],
        [0.1, 0.9, 0.4, 0.1],
        [0.2, 0.7, 0.7, 0.2]],

       [[0.4, 0.2, 0.9, 0.7],
        [0.1, 0.2, 0.4, 0.1],
        [0.7, 0.1, 0.4, 0.1],
        [0.9, 0.3, 0.5, 0.7]],

       [[0.3, 0.9, 0.2, 0.5],
        [0.9, 0.3, 0.2, 0.4],
        [0.6, 0.2, 0.9, 0.2],
        [0.1, 0.4, 0.8, 0.9]],

       [[0.3, 0.4, 0.2, 0.2],
        [0.4, 0.5, 0.6, 0.7],
        [0.6, 0.8, 0.5, 0.1],
        [0.2, 0.4, 0.2, 0.5]],

       [[0.2, 0.2, 0.9, 0.7],
        [0.3, 0.6, 0.3, 0.8],
        [0.7, 0.1, 0.2, 0.9],
        [0.6, 0.6, 0.6, 0.8]]])