In [1]:
import pandas as pd
import numpy as np
from imnfs.core import DecisionMaker
from imnfs.model import NFSet, RNF

data = pd.read_csv("data/experiment.csv") 

# Processing data

In [2]:
data1 = np.array(data[0:1])[0]
print(data1)
data2 = np.array(data[1:2])[0]
print(data2)

[ 8.6  6.   8.   6.   9.8  9.   3.   2.   9.8  7.   6.   5.   9.1  7.
  6.   8.   8.5  8.   5.   4.   9.8  9.   6.   5.   8.9  8.   5.   5.
  9.7  8.   4.   2.   9.8  9.   3.   2.   9.5  8.   3.   2.   8.8  8.
  5.   4.   9.7  6.   7.   6.   8.1  7.   5.   4.   9.6  9.   2.   2.
  9.8  5.   7.   7.   9.3  7.   8.   7.  10.   9.   3.   2.   9.7 10.
  1.   0.  10.   5.   7.   7.   9.9  5.   7.   8.   9.8  4.   8.   8.
 10.  10.   3.   2.  10.   5.   7.   7.   9.8 10.   3.   4. ]
[ 9.   7.   7.   4.   9.8 10.   2.   1.   9.5  8.   7.   6.   9.5  6.
  7.   7.   9.   7.   5.   4.   9.3  6.   7.   3.   9.5  5.   8.   8.
  9.9  9.   3.   4.  10.   9.   6.   2.  10.  10.   2.   1.   9.5  8.
  5.   3.   9.5  7.   6.   7.   8.8  9.   4.   4.   8.8  4.   8.   6.
  9.4  8.   7.   8.   9.8  9.   4.   5.   9.9 10.   1.   0.   9.7 10.
  3.   3.   9.7  6.   7.   6.   9.6  7.   8.   9.   8.6  9.   6.   5.
  9.7  8.   2.   2.   9.8  7.   7.   7.   9.7  8.   5.   4. ]


In [3]:
T10 = data1[0:4]
# print(T10)
L10 = data1[4:8]
H10 = data1[8:12]
A10 = np.mean(np.array([T10,L10,H10]),axis=0)
print(A10)

T11 = data1[32:36]
L11 = data1[36:40]
H11 = data1[40:44]
A11 = np.mean(np.array([T11,L11,H11]),axis=0)
print(A11)

T12 = data1[64:68]
L12 = data1[68:72]
H12 = data1[72:76]
A12 = np.mean(np.array([T12,L12,H12]),axis=0)
print(A12)

A = [A10,A11,A12]

T100 = data2[0:4]
L100 = data2[4:8]
H100 = data2[8:12]
A100 = np.mean(np.array([T100,L100,H100]),axis=0)
print(A100)

T110 = data2[32:36]
L110 = data2[36:40]
H110 = data2[40:44]
A110 = np.mean(np.array([T110,L110,H110]),axis=0)
print(A110)

T120 = data2[64:68]
L120 = data2[68:72]
H120 = data2[72:76]
A120 = np.mean(np.array([T12,L12,H12]),axis=0)

AA = [A100,A110,A120]

[9.4        7.33333333 5.66666667 4.33333333]
[9.36666667 8.33333333 3.66666667 2.66666667]
[9.9        8.         3.66666667 3.        ]
[9.43333333 8.33333333 5.33333333 3.66666667]
[9.83333333 9.         4.33333333 2.        ]


In [4]:
T10 = data1[0:4]
L10 = data1[4:8]
A10 = data1[28:32]
A110 = np.mean(np.array([T10,L10,A10]),axis=0)
print(A110)

T11 = data1[32:36]
L11 = data1[36:40]
A11 = data1[60:64]
A111 = np.mean(np.array([T11,L11,A11]),axis=0)
print(A111)

T12 = data1[64:68]
L12 = data1[68:72]
A12 = data1[92:96]
A112 = np.mean(np.array([T12,L12,A12]),axis=0)
print(A112)

A1 = [A110,A111,A112]

T100 = data2[0:4]
L100 = data2[4:8]
A100 = data2[28:32]
A1100 = np.mean(np.array([T100,L100,A100]),axis=0)
print(A110)

T110 = data2[32:36]
L110 = data2[36:40]
A110 = data2[60:64]
A1110 = np.mean(np.array([T110,L110,A110]),axis=0)
print(A1110)

T120 = data2[64:68]
L120 = data2[68:72]
A120 = data2[92:96]
A1120 = np.mean(np.array([T120,L120,A120]),axis=0)
print(A1120)

AA1 = [A1100,A1110,A1120]

[9.36666667 7.66666667 5.         3.33333333]
[9.53333333 8.         4.66666667 3.66666667]
[9.83333333 9.66666667 2.33333333 2.        ]
[9.36666667 7.66666667 5.         3.33333333]
[9.93333333 9.33333333 4.         2.66666667]
[9.76666667 9.33333333 3.         2.33333333]


In [5]:
T10 = data1[0:4]
H10 = data1[8:12]
SI10 = data1[12:16]
B10 = np.mean(np.array([T10,H10,SI10]),axis=0)
print(A10)

T11 = data1[32:36]
H11 = data1[40:44]
SI11 = data1[44:48]
B11 = np.mean(np.array([T11,H11,SI11]),axis=0)
print(B11)

T12 = data1[64:68]
H12 = data1[72:76]
SI12 = data1[76:80]
B12 = np.mean(np.array([T12,H12,SI12]),axis=0)
print(B12)

B = [B10,B11,B12]

T100 = data2[0:4]
H100 = data2[8:12]
SI100 = data2[12:16]
B100 = np.mean(np.array([T100,H100,SI100]),axis=0)
print(A100)

T110 = data2[32:36]
H110 = data2[40:44]
SI110 = data2[44:48]
B110 = np.mean(np.array([T110,H110,SI110]),axis=0)
print(B110)

T120 = data2[64:68]
H120 = data2[72:76]
SI120 = data2[76:80]
B120 = np.mean(np.array([T120,H120,SI120]),axis=0)
print(B120)

BB = [B100,B110,B120]

[9.7 8.  4.  2. ]
[9.43333333 7.66666667 5.         4.        ]
[9.96666667 6.33333333 5.66666667 5.66666667]
[9.9 9.  3.  4. ]
[9.66666667 8.         5.66666667 4.        ]
[9.73333333 7.66666667 5.33333333 5.        ]


In [6]:
V10 = data1[16:20]
SU10 = data1[20:24]
D10 = data1[24:28]
C10 = np.mean(np.array([V10,SU10,D10]),axis=0)
print(C10)

V11 = data1[48:52]
SU11 = data1[52:56]
D11 = data1[56:60]
C11 = np.mean(np.array([V11,SU11,D11]),axis=0)
print(C11)

V12 = data1[80:84]
SU12 = data1[84:88]
D12 = data1[88:92]
C12 = np.mean(np.array([V12,SU12,D12]),axis=0)
print(C12)

C = [C10,C11,C12]

V100 = data2[16:20]
SU100 = data2[20:24]
D100 = data2[24:28]
C100 = np.mean(np.array([V100,SU100,D100]),axis=0)
print(C100)

V110 = data2[48:52]
SU110 = data2[52:56]
D110 = data2[56:60]
C110 = np.mean(np.array([V110,SU110,D110]),axis=0)
print(C110)

V120 = data2[80:84]
SU120 = data2[84:88]
D120 = data2[88:92]
C120 = np.mean(np.array([V120,SU120,D120]),axis=0)
print(C120)

CC = [C100,C110,C120]

[9.06666667 8.33333333 5.33333333 4.66666667]
[9.16666667 7.         4.66666667 4.33333333]
[9.93333333 6.33333333 6.         5.66666667]
[9.26666667 6.         6.66666667 5.        ]
[9.         7.         6.33333333 6.        ]
[9.36666667 8.         5.         4.66666667]


In [7]:
T10 = data1[0:4]
V10 = data1[16:20]
A10 = data1[28:32]
DD10 = np.mean(np.array([T10,V10,A10]),axis=0)
print(DD10)

T11 = data1[32:36]
V11 = data1[48:52]
A11 = data1[60:64]
DD11 = np.mean(np.array([T11,V11,A11]),axis=0)
print(DD11)

T12 = data1[64:68]
V12 = data1[80:84]
A12 = data1[92:96]
DD12 = np.mean(np.array([T12,V12,A12]),axis=0)
print(DD12)

D = [DD10,DD11,DD12]

T100 = data2[0:4]
V100 = data2[16:20]
A100 = data2[28:32]
DD100 = np.mean(np.array([T100,V100,A100]),axis=0)
print(DD100)

T110 = data2[32:36]
V110 = data2[48:52]
A110 = data2[60:64]
DD110 = np.mean(np.array([T110,V110,A110]),axis=0)
print(DD110)

T120 = data2[64:68]
V120 = data2[80:84]
A120 = data2[92:96]
DD120 = np.mean(np.array([T120,V120,A120]),axis=0)
print(DD120)

DD = [DD100,DD110,DD120]

[8.93333333 7.33333333 5.66666667 4.        ]
[9.06666667 7.66666667 5.33333333 4.33333333]
[9.86666667 7.66666667 4.66666667 4.66666667]
[9.3        7.66666667 5.         4.        ]
[9.53333333 9.         4.66666667 3.66666667]
[9.4 9.  4.  3. ]


# Create NFSet

In [8]:
def change(A):
    Aok = []
    for i in range(3):
        temp = []
        for j in range(4):
            if j == 0:
                temp.append(A[i][j]/10)
            if j == 1:
                temp.append(A[i][j]/10)
            if j == 2:
                temp.append(A[i][j+1]/10)
            if j == 3:
                temp.append(A[i][j-1]/10)
        Aok.append(temp)
    return(Aok)

matrix = np.array([change(A),change(A1),change(B),change(C),change(D)])
matrixx = np.array([change(AA),change(AA1),change(BB),change(CC),change(DD)])

def rtc(A):
    rtc = []
    for i in range(3):
        temp = []
        for j in range(5):
            temp.append(A[j][i])
        rtc.append(temp)
    return np.array(rtc)
matric = rtc(matrix)
matricc = rtc(matrixx)

mat = []
for i in range(3):
    mat.append(matric[i])
    mat.append(matricc[i])
nfs = NFSet(mat)
print(nfs.data)

[[[0.94       0.73333333 0.43333333 0.56666667]
  [0.93666667 0.76666667 0.33333333 0.5       ]
  [0.91666667 0.66666667 0.63333333 0.66666667]
  [0.90666667 0.83333333 0.46666667 0.53333333]
  [0.89333333 0.73333333 0.4        0.56666667]]

 [[0.94333333 0.83333333 0.36666667 0.53333333]
  [0.95666667 0.86666667 0.3        0.4       ]
  [0.93333333 0.7        0.56666667 0.7       ]
  [0.92666667 0.6        0.5        0.66666667]
  [0.93       0.76666667 0.4        0.5       ]]

 [[0.93666667 0.83333333 0.26666667 0.36666667]
  [0.95333333 0.8        0.36666667 0.46666667]
  [0.94333333 0.76666667 0.4        0.5       ]
  [0.91666667 0.7        0.43333333 0.46666667]
  [0.90666667 0.76666667 0.43333333 0.53333333]]

 [[0.98333333 0.9        0.2        0.43333333]
  [0.99333333 0.93333333 0.26666667 0.4       ]
  [0.96666667 0.8        0.4        0.56666667]
  [0.9        0.7        0.6        0.63333333]
  [0.95333333 0.9        0.36666667 0.46666667]]

 [[0.99       0.8        0.3    

In [9]:
cost = []
rnf = RNF(nfs,cost)
print(rnf.data)

[[[0.94       0.73333333 0.43333333 0.56666667]
  [0.93666667 0.76666667 0.33333333 0.5       ]
  [0.91666667 0.66666667 0.63333333 0.66666667]
  [0.90666667 0.83333333 0.46666667 0.53333333]
  [0.89333333 0.73333333 0.4        0.56666667]]

 [[0.94333333 0.83333333 0.36666667 0.53333333]
  [0.95666667 0.86666667 0.3        0.4       ]
  [0.93333333 0.7        0.56666667 0.7       ]
  [0.92666667 0.6        0.5        0.66666667]
  [0.93       0.76666667 0.4        0.5       ]]

 [[0.93666667 0.83333333 0.26666667 0.36666667]
  [0.95333333 0.8        0.36666667 0.46666667]
  [0.94333333 0.76666667 0.4        0.5       ]
  [0.91666667 0.7        0.43333333 0.46666667]
  [0.90666667 0.76666667 0.43333333 0.53333333]]

 [[0.98333333 0.9        0.2        0.43333333]
  [0.99333333 0.93333333 0.26666667 0.4       ]
  [0.96666667 0.8        0.4        0.56666667]
  [0.9        0.7        0.6        0.63333333]
  [0.95333333 0.9        0.36666667 0.46666667]]

 [[0.99       0.8        0.3    

In [10]:
for i in range(9):
    result = DecisionMaker(rnf = rnf, index = i)
    print("Similarity no.",i+1,":", result.best_alternative())

[0.7053516694101845, 0.7429479897745598, 0.610901300829134, 0.603477045651687, 0.6673177830791099]
Similarity no. 1 : 2
[0.7612270929199969, 0.800476628723662, 0.6461379268588036, 0.6396269072414629, 0.717875676112053]
Similarity no. 2 : 2
[0.7265912129642125, 0.7654309538234566, 0.6226340190341474, 0.616500152923725, 0.6860790523080011]
Similarity no. 3 : 2
[0.7894246981352011, 0.8284089054333434, 0.6664218389851263, 0.659872911585397, 0.7444565249062584]
Similarity no. 4 : 2
[0.8075335216853864, 0.8457702419558015, 0.6803656235135016, 0.6736310389513067, 0.7620500093668714]
Similarity no. 5 : 2
[0.897335263218208, 0.9287418647004803, 0.7548987583803602, 0.7465841635522867, 0.8522321244577447]
Similarity no. 6 : 2
[0.720817308530215, 0.7594497273718042, 0.6191771296483387, 0.6108582469971663, 0.6809230633036993]
Similarity no. 7 : 2
[0.7186470133673262, 0.7572367644909527, 0.6175092394503414, 0.6117133161627003, 0.6789620075198011]
Similarity no. 8 : 2
[0.7814250538356332, 0.820809679